### ISSUE TITLE
Can't use sudo to run python in order to install python packages

### ISSUE THREAD

**Issue by LionSR** [embray/sage-windows#17]

**Comment by embray** [comment]
?

**Comment by LionSR** [comment]
Sorry, I solved this problem by open sage console as Administrator.

Terrific work! I really enjoy running sage on windows without using virtualbox. Sorry again as I am not familiar with cygwin.

**Comment by embray** [comment]
You probably shouldn't actually do that but for now it's fine--there's no protocol established for installing one's own packages into the Sage install; currently it's not technically supported but obviously you can do it if you raise your privileges.
