### ISSUE TITLE
Sage version

### ISSUE THREAD

**Issue by videlec** [embray/sage-windows#18]
Upgrading to newer Sage version:
- Sage 7.5 was released on January 11th (ans Sage 7.5.1 on January 15th)
- Sage 7.6 is about to be released

**Comment by embray** [comment]
Sage 7.5 and 7.6 don't work on Cygwin.  Sage 8.0 will be the next new version of the Windows release (and hopefully won't be skipped in the future).  Remember, the 7.4 release was always an alpha test.
